version: "3"

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./src/docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  backend-cms:
  # path to dockerfile
    build: .
    ports:
      - "3050:3050"
    volumes:
    # enables us to listen to changes 
      - ./:/app
    # makessure we have our node_modules
      - /app/node_modules
    # spin up DynamoDB image
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    environment:
      AWS_ACCESS_KEY_ID: 'local'
      AWS_SECRET_ACCESS_KEY: 'local'
      REGION: 'us-east-1'

  
